name: Despliegue Continuo jquiroz.net

on:
  push:
    branches:
      - master

  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  deploy:
    name: Despliegue servidor
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Ejecutar FASTAPI
      run: |
        ssh -o StrictHostKeyChecking=no toral@jquiroz.net << 'EOF'
          cd /home/toral/pruebas/actions
          git pull origin main
          source /home/toral/bash/calculadora-api/.venv/bin/activate
          pip install -r requirements.txt || pip install fastapi uvicorn

          fuser -k 3012/tcp || true
          nohup /home/toral/bash/calculadora-api/.venv/bin/uvicorn main:app --host 0.0.0.0 --port 3012 > fastapi.log 2>&1 &
        EOF
